# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'NOW直播' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NOW直播

pod 'MJRefresh'
pod 'Masonry'
pod 'WMPageController'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod ‘YYModel’
pod 'MLeaksFinder'
pod 'PPNetworkHelper'
pod 'BarrageRenderer'

end
